sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t tejks/docker-react-travis -f Dockerfile.dev .

script:
  - docker run -e CI=true tejks/docker-react-travis npm run test